version: 0.0
os: linux
files:
  - source: target/gs-spring-boot-docker-0.1.0.jar
    destination: /tmp
hooks:
  BeforeInstall
  - location: codedeploy/before_install.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: codedeploy/start_server.sh
    timeout: 300
    runas: root